language: python

# set Python versions to be tested on
python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9

# install and update pip, clone bandit repo
before_install:
  - echo "Upgrading pip"
  - python3 -m pip install --upgrade pip

# install all required libraries and dependancies
install:
  - echo "Install project dependancies and requirements"
  - if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
  - pip3 install codecov
  - pip3 install coverage
  - pip3 install pytest
  - pip3 install pytest-cov
  - pip3 install flake8 pytest
  - pip3 install bandit
  - pip3 install safety
  - pip3 install pydot
  - pip3 install pydotplus
  - pip3 install Cython
  - pip3 install google-cloud
  - pip3 install google-cloud-storage
  - pip3 install graphviz
  - sudo apt-get install graphviz


#   TRAVIS_ALLOW_FAILURE:
# set to true if the job is allowed to fail.
script:
  - echo "Running unit tests..."
  - python3 -m unittest discover
  - echo "Running pytest tests..."
  - python3 -m pytest tests/
  - echo "Running flake8 tests..."
  - flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
  - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
  - echo "Running Bandit tests..."
  # - ./bandit/scan.sh
  - echo "Running coverage report..."
  # - pytest --cov-report term --cov=psp tests/
  # - python3 -m safety check > package_safety_output.txt
  - echo "Running model locally"
  - python3 main.py --config="dummy"
  
after_success:
  - codecov
  - coveralls
  - echo "Build success"
