##################################################################################
## GCP Config file for setting machine instance types used for running models   ##
## https://cloud.google.com/compute/docs/machine-types#predefined_machine_types ##
##################################################################################


####Training Using High Memory n1 machine types####
trainingInput:
  scaleTier: CUSTOM
  masterType: n1-highmem-8
  runtimeVersion: '2.1'
  pythonVersion: '3.7'


#### Training Using GPU's ####
      # trainingInput:
      #   scaleTier: BASIC_GPU    # n1-standard-8 with one k80 GPU - OOM
      #   runtimeVersion: '2.1'
      #   pythonVersion: '3.7'
          # scaleTier: CUSTOM
          # masterType: standard_p100   1 (P100 GPU)  - OOM
          # masterType: complex_model_m_gpu - Quota failure

      # trainingInput:
      #   scaleTier: CUSTOM    # n1-standard-8 with one k80 GPU - OOM
      #   runtimeVersion: '2.1'
      #   pythonVersion: '3.7'
      #   masterType: cloud_tpu

      # trainingInput:
      #   scaleTier: CUSTOM    # n1-standard-8 with one k80 GPU - OOM
      #   runtimeVersion: '2.1'
      #   pythonVersion: '3.7'
      #   masterType: complex_model_m_gpu

      # trainingInput:
      #   scaleTier: CUSTOM           #OOM
      #   masterType: complex_model_m
      #   workerType: cloud_tpu
      #   workerCount: 4

#### Training Using TPU's ####
      #https://cloud.google.com/ai-platform/training/docs/using-tpus#configuring_a_custom_tpu_machine

      # trainingInput:
      #   scaleTier: BASIC_TPU    # n1-standard-4, workers: Cloud TPU (8 TPU v2 cores)
      #   runtimeVersion: '2.1'
      # #   pythonVersion: '3.7'
      # trainingInput:
      #   scaleTier: CUSTOM
      #   masterType: n1-highcpu-16
      #   workerType: cloud_tpu
      #   workerCount: 1
      #   workerConfig:
      #     acceleratorConfig:
      #       type: TPU_V2
      #       count: 8

#### Basic Training Configuration - Used for quickly testing things ####
      # trainingInput:
      #   scaleTier: BASIC

#### Training Using 50% of dataset ####
      # trainingInput:
      #   scaleTier: CUSTOM
      #   masterType: n1-highmem-8
      #   runtimeVersion: '2.1'
      #   pythonVersion: '3.7'

#### Training Using 25% of dataset ####
      # trainingInput:
      #   scaleTier: CUSTOM
      #   masterType: n1-highmem-4
      #   runtimeVersion: '2.1'
      #   pythonVersion: '3.7'

#### High Memory Throughput ####
      # trainingInput:
      #   scaleTier: CUSTOM
      #   masterType: n1-highmem-16
      #   workerType: n1-highmem-16
      #   parameterServerType: n1-highmem-16
      #   workerCount: 9
      #   parameterServerCount: 6
      #   runtimeVersion: '2.1'
      #   pythonVersion: '3.7'
